remote_theme: just-the-docs/just-the-docs
title: Memory Forward
description: Internal Knowledge Base

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
